# Generated by Django 5.1.4 on 2026-08-10 04:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('categories', '0001_initial'),
        ('goals', '0002_alter_goal_current_amount_alter_goal_target_amount'),
        ('transactions', '0004_recurringtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='txn_user_date_idx',
            old_name='transaction_user_id_8af7f1_idx',
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='next_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active', 'next_date'], name='rec_txn_user_act_next_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'date'], name='txn_user_cat_date_idx'),
        ),
    ]
