# Generated by Django 6.0.8 on 2026-08-13 12:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('merchants', '0001_initial'),
        ('tags', '0001_initial'),
        ('transactions', '0005_rename_transaction_user_id_8af7f1_idx_txn_user_date_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='card',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='auto_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='merchants.merchant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='tags.tag'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('biweekly', 'Har 2 hafta'), ('monthly', 'Oylik'), ('quarterly', 'Choraklik'), ('yearly', 'Yillik')], default='monthly', max_length=20),
        ),
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='transactions.transaction')),
            ],
        ),
    ]
