# Generated by Django 6.0.8 on 2026-08-13 12:04

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_user_category_month_year_budget',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='amount_limit',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='budget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_rollover',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budget',
            name='period',
            field=models.CharField(choices=[('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='budget',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 8, 13)),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'period', 'start_date'), name='unique_user_category_period_start_budget'),
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
    ]
