# Generated by Django 6.0.8 on 2026-08-13 12:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_goal_current_amount_alter_goal_target_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='auto_save',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='auto_save_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='goal',
            name='auto_save_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Haftalik'), ('monthly', 'Oylik')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2),
        ),
    ]
